main: me.func.App
name: ArcadeLobby
version: 1.0.0
depend:
  - CoreAPI
commands:
  menu:
    description: Открывает меню персонализации
    usage: /<menu>
  lootboxsound:
    description: Проигрывает звук открытия лутбокса
    usage: /<lootboxsound>
  leave:
    description: Возвращает вас в хаб
    usage: /<leave>
  battlepass:
    description: Показывает вам BattlePass
    usage: /<battlepass>
  play:
    description: Открывает компасс
    usage: /<play>