main: me.func.App
name: ArcadeLobby
version: 1.0.0
depend:
  - CoreAPI
commands:
  menu:
    description: Открывает меню персонализации
    usage: /<menu>
  lootboxsound:
    description: Проигрывает звук открытия лутбокса
    usage: /<lootboxsound>
  leave:
    description: Возвращает вас в хаб
    usage: /<leave>
  battlepass:
    description: Показывает вам BattlePass
    usage: /<battlepass>
  play:
    description: Открывает компасс
    usage: /<play>
  random:
    description: Запускает случайную очередь
    usage: /<random>
  queue:
    description: Игра!!!
    usage: /<queue>
  reroll:
    description: Сбросить задания BattlePass
    usage: /<reroll>
  lootbox:
    description: Выдать себе лутбокс
    usage: /<lootbox>
  money:
    description: Выдать себе денег
    usage: /<money> <value>
  exp:
    description: Дает вам опыт BattlePass
    usage: /<exp> <player> <value>
  pers:
    description: Дает вам персу
    usage: /<pers> <player> <uuid>
  discord:
    description: Показывает вам ссылку на дискорд в чат
    usage: /<discord>
  bpgive:
    description: Выдать баттлпасс игроку
    usage: /<bpgive> <exp/advanced> <nick>