package me.func

import me.func.battlepass.BattlePassUtil
import me.func.donate.impl.*
import me.func.mod.battlepass.BattlePass
import me.func.mod.battlepass.BattlePass.sale
import me.func.mod.battlepass.BattlePassPageAdvanced
import me.func.protocol.battlepass.BattlePassUserData
import org.bukkit.Material
import org.bukkit.entity.Player
import org.bukkit.inventory.ItemStack
import java.util.function.Function

object BattlePassManager {

    private val battlepass = BattlePass.new(399) {
        pages = mutableListOf(
            BattlePassPageAdvanced(
                300,
                10,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG1.getIcon(),
                    Mask.COMEDY_MASK.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG3.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.HORROR.getIcon()
                ),
                listOf(
                    NameTag.TAG2.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG4.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.TRADEGY.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.SLIME.getIcon()
                ),
            ), BattlePassPageAdvanced(
                600,
                20,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.GAS_MASK.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.STONE),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG4.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Corpse.G1.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG5.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.SLIME.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG6.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon()
                ),
            ), BattlePassPageAdvanced(
                900,
                30,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    KillMessage.GLOBAL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.WATER_DROP.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG7.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.STONE),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    StepParticle.SLIME.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG8.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    KillMessage.AHEAD.getIcon()
                ),
            ), BattlePassPageAdvanced(
                1200,
                40,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG9.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    KillMessage.END.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.STONE),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG10.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG11.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.DALLAS.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    StepParticle.FALLING_DUST.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                1500,
                50,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG12.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    KillMessage.SLEEP.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.SPELL_INSTANT.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.HOUSTON.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG13.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.CHAINS.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    KillMessage.HORNY.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG14.getIcon(),
                    MoneyKit.NORMAL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                1800,
                60,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG15.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.REDSTONE.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG16.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.FOXI.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    Mask.CHICA.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    StepParticle.REDSTONE.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.BONNIE.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    NameTag.TAG17.getIcon()
                ),
            ), BattlePassPageAdvanced(
                2100,
                70,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG18.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.VILLAGER_ANGRY.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    StepParticle.VILLAGER_ANGRY.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.DIVER_HELMET.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Corpse.G2.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    Mask.RAPHAEL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    StepParticle.VILLAGER_ANGRY.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    Mask.MICHELANGELO.getIcon()
                ),
            ), BattlePassPageAdvanced(
                2400,
                80,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG19.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.LEONARDO.getIcon(),
                    KillMessage.ROOM.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG21.getIcon(),
                    ArrowParticle.SPELL_WITCH.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG20.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    ArrowParticle.VILLAGER_HAPPY.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    StepParticle.FLAME.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    KillMessage.BLACK.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                2700,
                90,
                listOf(
                    MoneyKit.NORMAL.getIcon(),
                    NameTag.TAG22.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.DONATELLO.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.SCREAM.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG23.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.CREWMATE_ORANGE.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    Mask.CREWMATE_WHITE.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG24.getIcon()
                ),
            ), BattlePassPageAdvanced(
                3000,
                100,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.STONE),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG25.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.CREWMATE_YELLOW.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    NameTag.TAG26.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.NORMAL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.LAVA.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG27.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    KillMessage.X.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                3300,
                110,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    NameTag.TAG28.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.STONE),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    NameTag.TAG29.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.JASON.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.NOTE.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG30.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.EMOJI.getIcon(),
                    MoneyKit.BIG.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG31.getIcon()
                ),
            ), BattlePassPageAdvanced(
                3600,
                120,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    Mask.FREDDY.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.HEAR.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    NameTag.TAG32.getIcon(),
                    Corpse.G3.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    Mask.ONI.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    KillMessage.KIRA.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.BIG.getIcon()
                ),
            ), BattlePassPageAdvanced(
                3900,
                130,
                listOf(
                    MoneyKit.BIG.getIcon(),
                    Mask.CREWMATE_RED.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG33.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.STONE),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.BIG.getIcon(),
                    Mask.CREWMATE_PURPLE.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.CREWMATE_PINK.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    NameTag.TAG34.getIcon(),
                    LootboxUnit.getIcon()
                ),
            ), BattlePassPageAdvanced(
                4200,
                140,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG35.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG36.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.BIG.getIcon(),
                    Mask.CREWMATE_LIME.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    Mask.SAW.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.BIG.getIcon(),
                    LootboxUnit.getIcon(),
                    Corpse.G4.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG37.getIcon(),
                    MoneyKit.BIG.getIcon()
                ),
            ), BattlePassPageAdvanced(
                4500,
                150,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.BIG.getIcon(),
                    NameTag.TAG38.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.AHRI.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.IRON_BLOCK)
                ),
                listOf(
                    MoneyKit.NORMAL.getIcon(),
                    NameTag.TAG39.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.TIK_TOK.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.STAR_PLATINUM.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    StepParticle.NOTE.getIcon(),
                    MoneyKit.BIG.getIcon(),
                    ItemStack(Material.GOLD_BLOCK)
                )
            )
        )
        sale(20.0)
        facade.tags.add("Выполняйте квесты - получайте призы!")
        facade.tags.add("BattlePass завершится в 01.04.2022")
        questStatusUpdater = Function { player ->
            BattlePassUtil.getQuestLore(player)
        }
    }

    fun show(player: Player) {
        BattlePass.send(player, battlepass)
        var progress = Arcade.getArcadeData(player).progress

        if (progress == null)
            progress = BattlePassUserData(5, false)

        BattlePass.show(player, battlepass, progress)
    }
}