package me.func

import me.func.battlepass.BattlePassUtil
import me.func.donate.impl.*
import me.func.mod.battlepass.BattlePass
import me.func.mod.battlepass.BattlePass.sale
import me.func.mod.battlepass.BattlePassPageAdvanced
import me.func.protocol.battlepass.BattlePassUserData
import org.bukkit.Material
import org.bukkit.entity.Player
import org.bukkit.inventory.ItemStack
import java.util.function.Function

object BattlePassManager {

    private val battlepass = BattlePass.new(399) {
        pages = mutableListOf(
            BattlePassPageAdvanced(
                300,
                10,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG1.getIcon(),
                    Mask.COMEDY_MASK.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG3.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.HORROR.getIcon()
                ),
                listOf(
                    NameTag.TAG2.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG4.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.TRADEGY.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.SLIME.getIcon()
                ),
            ), BattlePassPageAdvanced(
                600,
                20,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.GAS_MASK.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.STONE),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG4.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG5.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.SLIME.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG6.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Corpse.G1.getIcon()
                ),
            ), BattlePassPageAdvanced(
                900,
                30,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    KillMessage.GLOBAL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.WATER_DROP.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG7.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.STONE),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    StepParticle.SLIME.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG8.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    KillMessage.AHEAD.getIcon()
                ),
            ), BattlePassPageAdvanced(
                1200,
                40,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG9.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    KillMessage.END.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.STONE),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG10.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG11.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.DALLAS.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    StepParticle.FALLING_DUST.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                1500,
                50,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG12.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    KillMessage.SLEEP.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.SPELL_INSTANT.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.HOUSTON.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG13.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.CHAINS.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    KillMessage.HORNY.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG14.getIcon(),
                    MoneyKit.NORMAL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                1800,
                60,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG15.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ArrowParticle.REDSTONE.getIcon(),
                    LootboxUnit.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    NameTag.TAG16.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.FOXI.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    Mask.CHICA.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    StepParticle.REDSTONE.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    Mask.BONNIE.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.NORMAL.getIcon(),
                    NameTag.TAG17.getIcon()
                ),
            ), BattlePassPageAdvanced(
                2100,
                70,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                2400,
                80,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                2700,
                90,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                3000,
                100,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                3300,
                110,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                3600,
                120,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                3900,
                130,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                4200,
                140,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon()
                ),
            ), BattlePassPageAdvanced(
                4500,
                150,
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.IRON_BLOCK)
                ),
                listOf(
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    MoneyKit.SMALL.getIcon(),
                    ItemStack(Material.GOLD_BLOCK)
                )
            )
        )
        sale(20.0)
        facade.tags.add("Выполняйте квесты - получайте призы!")
        facade.tags.add("BattlePass завершится в 01.04.2022")
        questStatusUpdater = Function { player ->
            BattlePassUtil.getQuestLore(player)
        }
    }

    fun show(player: Player) {
        BattlePass.send(player, battlepass)
        var progress = Arcade.getArcadeData(player).progress

        if (progress == null)
            progress = BattlePassUserData(5, false)

        BattlePass.show(player, battlepass, progress)
    }
}